import { StyleSheet } from "react-native";
import { colors } from "./common.styles";
export const profileStyles = StyleSheet.create({
  textsection: {
    alignItems: "center",
    paddingBottom: 10,
  },
  list: { flexGrow: 1, paddingBottom: 24 },
  eventCard: { marginBottom: 10, overflow: "hidden" },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginBottom: 6,
    gap: 5,
  },
  badgeDot: { width: 7, height: 7, borderRadius: 4 },
  badgeText: { fontSize: 11, fontWeight: "700", letterSpacing: 0.5 },

  empty: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  loadMoreBtn: { alignItems: "center", paddingVertical: 16 },

  profileCard: {
    alignItems: "center",
    overflow: "hidden",
    paddingVertical: 24,
  },
  avatarWrapper: { position: "relative", marginVertical: 13 },
  avatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    borderColor: colors.gray400,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarImage: { width: "100%", height: "100%" },
  editIcon: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#e8341a",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  profileName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111",
    letterSpacing: 1,
    marginBottom: 10,
    textAlign: "center",
  },
  editButton: { minWidth: 160 },
  errorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 10,
  },

  scroll: { flex: 1 },
  content: {  flexGrow:1,paddingHorizontal: 12, paddingBottom: 40 },

  avatarFallback: {
    backgroundColor: "#e0e0e0",
    alignItems: "center",
    justifyContent: "center",
  },
  initials: {
    fontSize: 32,
    fontWeight: "700",
    color: "#555",
    letterSpacing: 1,
  },
  cameraBtn: {
    position: "absolute",
    bottom: 2,
    right: 2,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 4,
  },
  removeBtn: {
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  removeBtnText: { fontSize: 13, color: colors.primary, fontWeight: "600" },

  sectionHeader: {  marginBottom: 8 },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#888",
    letterSpacing: 1.5,
  },
  sectionSubtitle: { fontSize: 12, color: "#aaa", marginTop: 2 },
  sectionLine: { height: 1, backgroundColor: "#f0f0f0", marginTop: 6 },

  readOnlyHint: {
    fontSize: 12,
    color: "#aaa",
    marginTop: -4,
    marginBottom: 8,
    marginLeft: 4,
  },

  saveBtn: { marginTop: 28 },
  saveBtnDisabled: { opacity: 0.6 },

  successBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 14,
    padding: 12,
    backgroundColor: "#f1f8e9",
    borderRadius: 8,
  },
  successText: { fontSize: 14, color: "#2e7d32", fontWeight: "600" },
});
